#
#Tue Mar 31 10:44:32 GMT 2026
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_httpTimeoutNumValues=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_snmpRetries0=2
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_EndNumValues=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizMonitorCore_automaticMode=0
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_ipPimgTimeout0=2000
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_Start0=10.1.0.1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_httpRetries0=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_useDefaults0=yes
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizIpPhoneSecurity_NBXSec=0
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_snmpTimeoutNumValues=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizDiscoveryOptions_UsingDefaults=0
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizNetworkSecurity_netSelectSNMPv1=true
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizNetworkSecurity_netWriteNumValues=0
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_wNetApiTimeout0=6000
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_Mask0=255.255.0.0
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_wNetApiTimeoutNumValues=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_IP0=10.1.0.0
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_snmpTimeout0=3000
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizNetworkSecurity_netUsersNumValues=0
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_httpRetriesNumValues=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_useDefaultsNumValues=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizIpPhoneSecurity_NBXAddressNumValues=0
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_StartNumValues=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizDiscoType_discoType=2
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_httpTimeout0=30000
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_ipPingRetriesNumValues=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_IPNumValues=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizDiscoveryOptions_NonDefaultValue=3
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizNetworkSecurity_netReadNumValues=0
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizIpPhoneSecurity_NBXUserNameNumValues=0
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_snmpRetriesNumValues=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizIpPhone_NBXPhoneSystem=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_ipPimgTimeoutNumValues=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_MaskNumValues=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_fullRange0=true
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_wNetApiRetriesNumValues=1
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_End0=10.1.255.254
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_ipPingRetries0=2
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_wNetApiRetries0=2
com.coms.wsd.tns.client.dialogs.discowizard.DiscoWizSpecifySubnets_fullRangeNumValues=1
